import { ETF, NewsItem, AIInsight, AIPerformance } from './types';

export const initialETFs: ETF[] = [
  {
    id: '1',
    symbol: 'SPY',
    name: 'SPDR S&P 500 ETF Trust',
    price: 527.43,
    prevPrice: 527.43,
    change: 6.21,
    changePercent: 1.19,
    volume: '78.5M',
    marketCap: '$486.2B',
    market: 'US',
    signal: 'BUY',
    confidence: 91,
    rsi: 62,
    macd: 'Bullish',
    trend: 'Uptrend',
    support: 518.50,
    resistance: 535.00
  },
  {
    id: '2',
    symbol: 'QQQ',
    name: 'Invesco QQQ Trust',
    price: 462.18,
    prevPrice: 462.18,
    change: 9.34,
    changePercent: 2.06,
    volume: '54.2M',
    marketCap: '$198.7B',
    market: 'US',
    signal: 'BUY',
    confidence: 94,
    rsi: 58,
    macd: 'Bullish',
    trend: 'Strong Uptrend',
    support: 450.00,
    resistance: 475.00
  },
  {
    id: '3',
    symbol: 'VOO',
    name: 'Vanguard S&P 500 ETF',
    price: 484.92,
    prevPrice: 484.92,
    change: 5.12,
    changePercent: 1.07,
    volume: '11.8M',
    marketCap: '$395.8B',
    market: 'US',
    signal: 'HOLD',
    confidence: 76,
    rsi: 54,
    macd: 'Neutral',
    trend: 'Sideways',
    support: 475.00,
    resistance: 495.00
  },
  {
    id: '4',
    symbol: 'VTI',
    name: 'Vanguard Total Stock Market',
    price: 268.54,
    prevPrice: 268.54,
    change: 2.87,
    changePercent: 1.08,
    volume: '7.9M',
    marketCap: '$338.4B',
    market: 'US',
    signal: 'BUY',
    confidence: 85,
    rsi: 56,
    macd: 'Bullish',
    trend: 'Uptrend',
    support: 260.00,
    resistance: 278.00
  },
  {
    id: '5',
    symbol: 'IWM',
    name: 'iShares Russell 2000 ETF',
    price: 212.30,
    prevPrice: 212.30,
    change: -1.45,
    changePercent: -0.68,
    volume: '26.1M',
    marketCap: '$58.2B',
    market: 'US',
    signal: 'HOLD',
    confidence: 62,
    rsi: 44,
    macd: 'Bearish',
    trend: 'Sideways',
    support: 205.00,
    resistance: 220.00
  },
  {
    id: '6',
    symbol: 'ARKK',
    name: 'ARK Innovation ETF',
    price: 52.67,
    prevPrice: 52.67,
    change: -2.10,
    changePercent: -3.83,
    volume: '19.4M',
    marketCap: '$6.8B',
    market: 'US',
    signal: 'SELL',
    confidence: 78,
    rsi: 32,
    macd: 'Bearish',
    trend: 'Downtrend',
    support: 48.00,
    resistance: 58.00
  },
  {
    id: '7',
    symbol: 'NIFTYBEES',
    name: 'Nippon India Nifty 50 BeES',
    price: 268.45,
    prevPrice: 268.45,
    change: 4.15,
    changePercent: 1.57,
    volume: '14.8M',
    marketCap: '₹18,542Cr',
    market: 'IN',
    signal: 'BUY',
    confidence: 88,
    rsi: 61,
    macd: 'Bullish',
    trend: 'Uptrend',
    support: 260.00,
    resistance: 280.00
  },
  {
    id: '8',
    symbol: 'BANKBEES',
    name: 'Nippon India Bank BeES',
    price: 482.30,
    prevPrice: 482.30,
    change: -2.80,
    changePercent: -0.58,
    volume: '9.2M',
    marketCap: '₹8,245Cr',
    market: 'IN',
    signal: 'HOLD',
    confidence: 69,
    rsi: 48,
    macd: 'Neutral',
    trend: 'Consolidation',
    support: 470.00,
    resistance: 495.00
  },
  {
    id: '9',
    symbol: 'GOLDBEES',
    name: 'Nippon India Gold BeES',
    price: 58.92,
    prevPrice: 58.92,
    change: 1.24,
    changePercent: 2.15,
    volume: '21.3M',
    marketCap: '₹12,847Cr',
    market: 'IN',
    signal: 'BUY',
    confidence: 83,
    rsi: 59,
    macd: 'Bullish',
    trend: 'Uptrend',
    support: 55.00,
    resistance: 62.00
  },
  {
    id: '10',
    symbol: 'ITBEES',
    name: 'Nippon India IT BeES',
    price: 42.18,
    prevPrice: 42.18,
    change: 1.08,
    changePercent: 2.63,
    volume: '6.1M',
    marketCap: '₹2,456Cr',
    market: 'IN',
    signal: 'BUY',
    confidence: 87,
    rsi: 63,
    macd: 'Bullish',
    trend: 'Strong Uptrend',
    support: 39.00,
    resistance: 46.00
  },
  {
    id: '11',
    symbol: 'DIA',
    name: 'SPDR Dow Jones Industrial',
    price: 398.75,
    prevPrice: 398.75,
    change: 3.42,
    changePercent: 0.87,
    volume: '4.2M',
    marketCap: '$32.1B',
    market: 'US',
    signal: 'HOLD',
    confidence: 71,
    rsi: 52,
    macd: 'Neutral',
    trend: 'Sideways',
    support: 390.00,
    resistance: 410.00
  },
  {
    id: '12',
    symbol: 'JUNIORBEES',
    name: 'Nippon India Junior BeES',
    price: 812.45,
    prevPrice: 812.45,
    change: 12.30,
    changePercent: 1.54,
    volume: '3.8M',
    marketCap: '₹4,521Cr',
    market: 'IN',
    signal: 'BUY',
    confidence: 82,
    rsi: 58,
    macd: 'Bullish',
    trend: 'Uptrend',
    support: 790.00,
    resistance: 840.00
  }
];

export const newsItems: NewsItem[] = [
  {
    id: 1,
    title: 'Fed Signals Potential Rate Cuts in Q2 2024',
    summary: 'Federal Reserve indicates dovish stance as inflation shows signs of cooling. Markets rally on expectations of monetary easing.',
    sentiment: 'bullish',
    source: 'Bloomberg',
    time: '5 min ago',
    impact: 'high'
  },
  {
    id: 2,
    title: 'AI Sector Sees Massive Institutional Inflows',
    summary: 'Tech ETFs surge as major funds increase allocation to artificial intelligence and semiconductor stocks.',
    sentiment: 'bullish',
    source: 'Reuters',
    time: '18 min ago',
    impact: 'high'
  },
  {
    id: 3,
    title: 'India GDP Growth Beats Estimates at 7.3%',
    summary: 'Indian economy shows robust growth, Nifty 50 hits fresh all-time highs. Foreign investors increase exposure.',
    sentiment: 'bullish',
    source: 'Economic Times',
    time: '42 min ago',
    impact: 'high'
  },
  {
    id: 4,
    title: 'Crude Oil Spikes on Middle East Tensions',
    summary: 'Energy costs rise as geopolitical risks intensify. Analysts warn of potential supply disruptions.',
    sentiment: 'bearish',
    source: 'CNBC',
    time: '1 hour ago',
    impact: 'medium'
  },
  {
    id: 5,
    title: 'US Treasury Yields Ease on Soft Inflation Data',
    summary: 'Bond markets rally as CPI comes in below expectations. Growth stocks benefit from lower rate outlook.',
    sentiment: 'bullish',
    source: 'Wall Street Journal',
    time: '2 hours ago',
    impact: 'medium'
  },
  {
    id: 6,
    title: 'China Manufacturing PMI Disappoints',
    summary: 'Economic slowdown deepens in China. Export-dependent sectors face headwinds.',
    sentiment: 'bearish',
    source: 'Financial Times',
    time: '3 hours ago',
    impact: 'medium'
  },
  {
    id: 7,
    title: 'RBI Maintains Repo Rate, Signals Caution',
    summary: 'Indian central bank holds rates steady, maintains accommodative stance for growth.',
    sentiment: 'neutral',
    source: 'Mint',
    time: '4 hours ago',
    impact: 'medium'
  },
  {
    id: 8,
    title: 'Tech Earnings Beat Street Estimates',
    summary: 'Major tech companies report strong quarterly results, driving sector momentum.',
    sentiment: 'bullish',
    source: 'TechCrunch',
    time: '5 hours ago',
    impact: 'high'
  }
];

export const aiInsights: AIInsight[] = [
  {
    id: 1,
    type: 'opportunity',
    title: 'Strong Buy Signal: QQQ',
    description: 'MACD crossover confirmed with volume surge 23% above 20-day average. RSI at 58 indicates momentum without overbought conditions. AI projects 8.5% upside to $500 target.',
    confidence: 94,
    etfSymbol: 'QQQ'
  },
  {
    id: 2,
    type: 'risk',
    title: 'High Volatility Alert: ARKK',
    description: 'RSI at 32 showing oversold conditions but no reversal signal yet. High beta (1.8) amplifies market moves. Consider reducing position size or setting stop-loss at $48.',
    confidence: 78,
    etfSymbol: 'ARKK'
  },
  {
    id: 3,
    type: 'info',
    title: 'Sector Rotation Detected',
    description: 'Institutional flows shifting from value to growth. AI/semiconductor leadership emerging. Consider overweighting QQQ and tech-heavy ETFs in current environment.',
    confidence: 86
  },
  {
    id: 4,
    type: 'opportunity',
    title: 'India Markets Breakout',
    description: 'NIFTYBEES showing strong momentum with FII inflows. GDP data supports bullish thesis. AI recommends 15% portfolio allocation to India ETFs.',
    confidence: 88,
    etfSymbol: 'NIFTYBEES'
  },
  {
    id: 5,
    type: 'info',
    title: 'Gold Hedge Recommended',
    description: 'Geopolitical tensions and rate cut expectations favor gold. GOLDBEES provides effective portfolio hedge. Suggested allocation: 5-8% of portfolio.',
    confidence: 79,
    etfSymbol: 'GOLDBEES'
  }
];

export const aiPerformance: AIPerformance = {
  accuracy: 94.2,
  sharpeRatio: 2.41,
  winRate: 78.6,
  maxDrawdown: 8.2,
  totalSignals: 1247,
  successfulSignals: 980
};
